# Generated by Django 5.0.14 on 2026-06-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='files_json',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
