# Generated by Django 5.0.14 on 2026-06-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(default='external', max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('language', models.CharField(default='JavaScript', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('analyzing', 'Analyzing'), ('failed', 'Failed')], default='active', max_length=20)),
                ('last_analysis_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('total_issues', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
